FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf -y install httpd php \
  && microdnf clean all

ADD index.php /var/www/html

RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /run/php-fpm /var/run/php-fpm \
  && chmod -R g=u /var/log/httpd /var/run/httpd /run/php-fpm /var/run/php-fpm

RUN sed -i 's/\#/\;/' /etc/php-fpm.d/www.conf

RUN echo 'LoadModule mpm_prefork_module modules/mod_mpm_prefork.so' > /etc/httpd/conf.modules.d/00-mpm.conf
RUN sed -i 's|# LoadModule php7_module modules/libphp7-zts.so|LoadModule php7_module modules/libphp7-zts.so|' /etc/httpd/conf.modules.d/15-php.conf

EXPOSE 8080
USER 1001
CMD php-fpm & httpd -D FOREGROUND